spring:
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432}
    name: ${DB_NAME:joboffers}
    username: ${DB_USER:joboffers}
    password: ${DB_PASSWORD:joboffers}
  flyway:
    user: ${DB_USER:joboffers}
    password: ${DB_PASSWORD:joboffers}
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/joboffers}

services:
  company:
    url: ${COMPANY_SERVICE_URL:http://localhost:8081}
  job:
    url: ${JOB_SERVICE_URL:http://localhost:3000}

server:
  port: ${SERVER_PORT:8082}
