spring:
  r2dbc:
    url: ${R2DBC_URL}
    name: ${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${JDBC_URL}

services:
  company:
    url: ${COMPANIES_SERVICE_URL}
  job:
    url: ${JOBS_SERVICE_URL}

server:
  port: ${SERVER_PORT}
