spring:
  r2dbc:
    url: ${R2DBC_URL}
    name: ${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${JDBC_URL}

server:
  port: ${SERVER_PORT}

seasonlink:
  services:
    companies: ${COMPANIES_SERVICE_URL}
    jobs: ${JOBS_SERVICE_URL}

logging:
  level:
    web: debug

nats:
  url: ${NATS_URL}
