spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    name: ${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    jdbc: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

server:
  port: ${SERVER_PORT}

seasonlink:
  services:
    companies: ${COMPANIES_SERVICE_URL}
    jobs: ${JOBS_SERVICE_URL}

logging:
  level:
    web: info
