spring:
  r2dbc:
    url: r2dbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}
    name: ${PG_DATABASE}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  flyway:
    enabled: true
    check-location: true
    locations: classpath:db/migration
    user: ${PG_USER}
    password: ${PG_PASSWORD}
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}

server:
  port: ${SERVER_PORT}

seasonlink:
  services:
    companies: ${COMPANIES_SERVICE_URL}
    jobs: ${JOBS_SERVICE_URL}

logging:
  level:
    web: info
