apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "profiles.fullname" . }}
  labels:
    {{- include "profiles.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "profiles.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "profiles.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "profiles.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: PG_USER
              value: {{ .Values.postgresql.username }}
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.credentialsSecretName }}
                  key: {{ .Values.postgresql.credentialsSecretPasswordKey }}
            - name: PG_HOST
              value: {{ .Values.postgresql.host }}
            - name: PG_PORT
              value: {{ .Values.postgresql.port | quote }}
            - name: PG_DATABASE
              value: {{ .Values.postgresql.database }}
            - name: SERVER_PORT
              value: {{ .Values.service.port | quote }}
            - name: JOB_SERVICE_URL
              value: {{ .Values.jobServiceUrl }}
            - name: IMAGE_GENERATOR_SERVICE_URL
              value: {{ .Values.imageGeneratorServiceUrl }}
            - name: KEYCLOAK_URL
              value: {{ .Values.keycloak.url }}
            - name: KEYCLOAK_CLIENT_ID
              value: {{ .Values.keycloak.clientId }}
            - name: KEYCLOAK_SERVICE_ACCOUNT_USERNAME
              value: {{ .Values.keycloak.auth.user }}
            - name: KEYCLOAK_SERVICE_ACCOUNT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.auth.passwordSecretName }}
                  key: {{ .Values.keycloak.auth.passwordSecretKey }}
            - name: MINIO_URL
              value: {{ .Values.minio.url }}
            - name: MINIO_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.auth.secretName }}
                  key: {{ .Values.minio.auth.accessKey }}
            - name: MINIO_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.auth.secretName }}
                  key: {{ .Values.minio.auth.secretKey }}
            - name: MINIO_BUCKET_NAME
              value: {{ .Values.minio.bucketName }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
