quarkus:
  devservices:
    enabled: false

  datasource:
    db-kind: postgresql
    jdbc: false
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    reactive:
      url: vertx-reactive:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}

  hibernate-orm:
    database:
      generation: none
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  flyway:
    migrate-at-start: false

  http:
    port: 8080
    host: 0.0.0.0
