spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/season-link
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

seasonlink:
  services:
    jobs: http://localhost:8082
    job-offers: http://localhost:8083
    companies: http://localhost:8084
    applications: http://localhost:8085
    profiles: http://localhost:8086
    ratings: http://localhost:8087
    notifications: http://localhost:8088

server:
  port: 8081
