spring:
  r2dbc:
    url: r2dbc:postgresql://postgresql:5432
    name: joboffers
    username: postgres
    password: postgres
  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/joboffers
  docker:
    compose:
      enabled: false

seasonlink:
  services:
    companies: http://localhost:3000
    jobs: http://localhost:3000

server:
  port: 8080
