name: On Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions:
      packages: write
    name: Build
    uses: mmoreiradj/season-link/.github/workflows/build-all.yaml@make/ci

  update-chart:
    name: Update Chart Version
    uses: mmoreiradj/season-link/.github/workflows/update-chart-version.yaml@make/ci
    with:
      tag: ${{ github.ref }}